### ISSUE TITLE
Consider adding the VS Extension to open-vsx.org

### ISSUE THREAD

**Issue by gwelr** [glebbash/LO#15]
Curious about your project, I was trying to install the VS extension to VSCodium (https://github.com/VSCodium/vscodium),  a freely-licensed binaries of VS Code with a community-driven default configuration. Being a vscode based editor, VSCodium gets additional features by installing VS Code extensions. Unfortunately, as Microsoft  prohibits usages of the Microsoft marketplace by any other products (https://github.com/microsoft/vscode/issues/31168) or redistribution of .vsix files from it, in order to use VS Code extensions in non-Microsoft products those need to be installed differently.

For the rest of us using VS Code Compatible Editors, would you consider submitting the LO VS Code extension to OpenVSX (https://open-vsx.org)? Open VSX is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions.

Thanks!

**Comment by gwelr** [comment]
The process to submit the extension is describe here : https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by glebbash** [comment]
Looks like I won't need to support two versions.

Will publish this extension to open-vsx as soon as `wasm-wasi-core` [will be available](https://github.com/open-vsx/publish-extensions/pull/763#pullrequestreview-2132810027) on open-vsx.

**Comment by glebbash** [comment]
@gwelr the extension is finally available on Open VSX: https://github.com/glebbash/LO/blob/main/README.md#-vscode-extension
