### ISSUE TITLE
WASM WASI Core extension will move to a release version

### ISSUE THREAD

**Issue by dbaeumer** [glebbash/LO#16]
We decided to provide a release version of the WASM WASI Core extension and the wasm-wasi API npm module to ease the installation of extensions that depend on it.

To allow further improvements to the API the npm module wasm-wasi will provide different routes to import different API versions. The API provided by the default import `import { Wasm } from '@vscode/wasm-wasi'` is deprecated together with all other types from that route. The npm module exports new routes to be able to serve different API versions. The current route for the API (which is the same as before) is `import { Wasm } from '@vscode/wasm-wasi/v1'`. There might be new routes in the future to cover a v2 version of the API or a proposed route to test proposed API.

The v1 import works with the current pre-release version of the WASM WASI Core extension (e.g. 0.13.3) and will work with the upcoming release version of the WASM WASI Core extension (e.g. 1.0.0)

I ask that your extension starts using the new `@vscode/wasm-wasi@1.0.0-pre.2` version of the npm module to be prepared for the release of the WASM WASI Core extension.

If you encounter any problems please open issues here: https://github.com/microsoft/vscode-wasm/issues

**Comment by glebbash** [comment]
Thanks for the update @dbaeumer. Just updated the extension, confirmed that `@vscode/wasm-wasi@1.0.0-pre.2` works as expected.
