### ISSUE TITLE
Stack-allocated vectors only hold N - 1 elements

### ISSUE THREAD

**Issue by jaredkrinke** [glebbash/LO#17]
While using a stack-allocated vector, I noticed that if I specify a capacity of N, I can actually only push N - 1 items. It looks like `Vec::_grow_to_size` only allows `self.size < self.capacity` instead of `self.size <= self.capacity`

My code was something like this (it fails when run in wasmtime on the 5th add):

```lo
include "lib/cli.lo";

fn main() {
	let n = 5;
	let v = Vec::with_capacity_using(n, sizeof u32, alloc::STACK);
	for i in 0..n {
		puts("Adding ");
		print_u32(i);
		puts("\n");
		v.push!<u32>(1);
	};
};
```

Disclaimer: I'm pretty new to LO, so maybe I'm not understanding something correctly.

**Comment by glebbash** [comment]
Merged the PR. Thanks for contribution 👍
